---
## Github hosted runner 

name: Github-Action-Learning
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run Test
        run: |
          cd src
          python -m pytest addition.py
          